apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kiii-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: janagogs/backend:v2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: plantdiary-config
                  key: SPRING_DATA_MONGODB_URI
