name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        id: vars
        run: echo "branch_name=$(echo ${{ github.ref_name }} | tr '/' '-')" >> "$GITHUB_OUTPUT"

      - name: Set up Java (Backend)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Docker tag
        run: echo "${{ secrets.DOCKER_USERNAME }}/plantdiary-backend:${{ steps.vars.outputs.branch_name }}-latest"

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/plantdiary-backend:${{ steps.vars.outputs.branch_name }}-latest

      - name: Build & push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/plantdiary-frontend:${{ steps.vars.outputs.branch_name }}-latest

